# -*- coding: utf-8 -*-
"""Stargazer Wall — thanks the people who star Profile Verse.

Stateless & idempotent: every run fetches the full stargazer list from the
GitHub API (with starred_at timestamps), renders a wall, and updates a single
issue whose body IS the wall. New stars of the last 7 days are highlighted on
top. No state file, nothing to commit — the API is the source of truth.

Env: GH_TOKEN (required) · REPO (owner/name, default Morningstar202604/profile-verse)
"""

import datetime
import json
import os
import sys
import urllib.request

API = "https://api.github.com"
REPO = os.environ.get("REPO", "Morningstar202604/profile-verse")
TITLE = "\u2b50 Stargazer Wall \u00b7 \u611f\u8c22\u5899"
WEEK_DAYS = 7


def token():
    t = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN", "").strip()
    if not t:
        import netrc
        try:
            info = netrc.netrc().authenticators("api.github.com")
            if info:
                t = info[2]
        except Exception:  # noqa: BLE001
            pass
    return t


def gh(method, path, body=None):
    req = urllib.request.Request(API + path, method=method)
    req.add_header("Authorization", "token " + token())
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", "profile-verse-star-wall")
    data = None
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, data=data, timeout=30) as r:
            raw = r.read().decode("utf-8")
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as e:
        msg = e.read().decode("utf-8", "replace")
        raise RuntimeError("%s %s -> %s" % (method, path, msg[:300]))


def fetch_stargazers():
    """(login, starred_at) for every stargazer, oldest first."""
    stars = []
    page = 1
    while True:
        req = urllib.request.Request(
            API + "/repos/%s/stargazers?per_page=100&page=%d" % (REPO, page)
        )
        req.add_header("Authorization", "token " + token())
        req.add_header("Accept", "application/vnd.github.star+json")
        req.add_header("User-Agent", "profile-verse-star-wall")
        with urllib.request.urlopen(req, timeout=30) as r:
            batch = json.loads(r.read().decode("utf-8"))
        for s in batch:
            stars.append((s["user"]["login"], s.get("starred_at") or ""))
        if len(batch) < 100:
            break
        page += 1
    return stars


def render_wall(stars):
    now = datetime.datetime.now(datetime.timezone.utc)
    week_ago = (now - datetime.timedelta(days=WEEK_DAYS)).isoformat()
    weekly = [s for s in stars if s[1] and s[1] >= week_ago]
    lines = [
        "## \u2b50 Stargazer Wall \u00b7 \u611f\u8c22\u5899",
        "",
        "\u611f\u8c22\u6bcf\u4e00\u4f4d\u70b9\u4eae **Profile Verse** \u7684\u5f00\u53d1\u8005\uff0c"
        "\u4f60\u4eec\u8ba9\u661f\u7a7a\u66f4\u4eae\u3002",
        "",
        "\u5f53\u524d\u00b7 **%d** \u9897\u661f\u661f" % len(stars),
        "",
    ]
    if weekly:
        lines += ["### \u672c\u5468\u65b0\u661f", ""]
        for login, at in sorted(weekly, key=lambda s: s[1], reverse=True):
            lines.append("- \U0001f31f @%s \u00b7 %s" % (login, at[:10]))
        lines += [""]
    lines += ["### \u5168\u90e8\u661f\u5149", ""]
    for login, at in sorted(stars, key=lambda s: s[1], reverse=True):
        lines.append("- @%s \u00b7 %s" % (login, (at or "")[:10]))
    lines += ["", "---", "_Generated by [Profile Verse](https://github.com/%s) \u00b7 "
                   "\u6bcf\u5468\u81ea\u52a8\u66f4\u65b0_" % REPO]
    return "\n".join(lines)


def find_issue():
    q = "repo:%s \"%s\" in:title is:issue" % (REPO, TITLE.split(" · ")[0])
    import urllib.parse
    d = gh("GET", "/search/issues?q=" + urllib.parse.quote(q))
    for item in d.get("items", []):
        if item.get("title") == TITLE:
            return item["number"]
    return None


def main():
    stars = fetch_stargazers()
    body = render_wall(stars)
    num = find_issue()
    if num:
        gh("PATCH", "/repos/%s/issues/%d" % (REPO, num), {"body": body})
        action = "updated #%d" % num
    else:
        d = gh("POST", "/repos/%s/issues" % REPO, {"title": TITLE, "body": body})
        num = d.get("number")
        action = "created #%d" % num
    print("OK: %d stargazers, %s (%s)" % (len(stars), action, datetime.date.today().isoformat()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
